/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'anx00283' at '4/27/17 2:43 PM' with Gradle 2.11
 *
 * @author anx00283, @date 4/27/17 2:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
